-- 메시지 수신 테이블

CREATE TABLE `DHN_RECEPTION` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `msgid` varchar(20) DEFAULT NULL COMMENT '메시지 ID',
  `userid` varchar(20) DEFAULT NULL COMMENT '유저 ID',
  `insert_date` timestamp NULL DEFAULT current_timestamp() COMMENT '삽입 날짜',
  PRIMARY KEY (`id`),
  KEY `DHN_RECEPTION_msgid_IDX` (`msgid`,`userid`) USING BTREE,
  KEY `DHN_RECEPTION_userid_IDX` (`userid`,`msgid`,`insert_date`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='수신 테이블';

-- 발송계정 세팅용 DHN_CLIENT_LIST 테이블

CREATE TABLE `DHN_CLIENT_LIST` (
  `user_id` varchar(50) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `use_flag` char(1) DEFAULT NULL,
  /* `port` char(5) NOT NULL DEFAULT '9090' */
  `send_limit` varchar(50) DEFAULT NULL,
  `sms_len_check` char(1) DEFAULT 'N',
  `oshot` varchar(100) NOT NULL DEFAULT 'OShot' COMMENT 'oshot 발송 삽입 테이블',
  `dest` varchar(100) DEFAULT NULL COMMENT '발송 목적지(OSHOT(NULL), NANO)',
  `alimtalk` varchar(1) DEFAULT NULL COMMENT '알림톡사용유무',
  `friendtalk` varchar(1) DEFAULT 'N' COMMENT '친구톡사용유무',
  /* `second_send_flag` enum('Y','N') DEFAULT 'Y' COMMENT '2차 발송 플래그', */
  /* `crypto` varchar(255) DEFAULT NULL COMMENT '암호화 컬럼(구분자 , 공백없이)', */
  `nano_tel_seperate` char(1) DEFAULT 'N' COMMENT '나노 010 분리 작업',
  /* `pre_send_type` tinyint(4) DEFAULT 0 COMMENT 'API를 이용한 문자발송 플랫폼 전환 했을 때 전 발송 플랫폼(0 : 에이전트 가동 후 변경X, 1 : oshot, 2 : nano)',
  `pre_update_date` timestamp NULL DEFAULT NULL COMMENT 'API를 이용한 문자발송 플랫폼 전환 했을 때의 시간', */
  `description` varchar(500) DEFAULT NULL COMMENT '업체에 대한 설명 및 비고란'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 친구톡 발송용 DHN_REQUEST 테이블

CREATE TABLE `DHN_REQUEST` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `msgid` varchar(32) NOT NULL,
  `userid` varchar(20) NOT NULL,
  `ad_flag` varchar(1) DEFAULT NULL,
  `button1` longtext DEFAULT NULL,
  `button2` longtext DEFAULT NULL,
  `button3` longtext DEFAULT NULL,
  `button4` longtext DEFAULT NULL,
  `button5` longtext DEFAULT NULL,
  `image_link` longtext DEFAULT NULL,
  `image_url` longtext DEFAULT NULL,
  `message_type` varchar(2) DEFAULT NULL,
  `msg` longtext NOT NULL,
  `msg_sms` longtext DEFAULT NULL,
  `only_sms` varchar(1) DEFAULT NULL COMMENT 'N : 카카오 전용, Y : SMS 전용, D : 카카오 발송후 실패시 SMS',
  `phn` varchar(15) NOT NULL,
  `profile` varchar(50) DEFAULT NULL,
  `p_com` varchar(2) DEFAULT NULL,
  `p_invoice` varchar(100) DEFAULT NULL,
  `reg_dt` varchar(20) NOT NULL,
  `remark1` varchar(50) DEFAULT NULL,
  `remark2` varchar(50) DEFAULT NULL,
  `remark3` varchar(50) DEFAULT NULL,
  `remark4` varchar(50) DEFAULT NULL,
  `remark5` varchar(50) DEFAULT NULL,
  `reserve_dt` varchar(14) NOT NULL,
  `sms_kind` varchar(1) DEFAULT NULL,
  `sms_lms_tit` varchar(120) DEFAULT NULL,
  `sms_sender` varchar(15) DEFAULT NULL,
  `s_code` varchar(2) DEFAULT NULL,
  `tmpl_id` varchar(30) DEFAULT NULL,
  `wide` varchar(1) DEFAULT NULL,
  `send_group` char(20) DEFAULT NULL,
  `supplement` text DEFAULT NULL,
  `price` int(11) DEFAULT 0,
  `currency_type` char(3) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `header` varchar(100) DEFAULT NULL,
  `carousel` longtext DEFAULT NULL,
  `attachments` text DEFAULT NULL,
  `att_items` text DEFAULT NULL,
  `att_coupon` text DEFAULT NULL,
  `mms_image_id` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `msgid` (`msgid`) USING BTREE,
  KEY `send_group` (`send_group`) USING BTREE,
  KEY `DHN_REQUEST_send_group_IDX` (`send_group`,`reserve_dt`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 알림톡 발송용 DHN_REQUEST_AT 테이블

CREATE TABLE `DHN_REQUEST_AT` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `msgid` varchar(32) NOT NULL,
  `userid` varchar(20) NOT NULL,
  `ad_flag` varchar(1) DEFAULT NULL,
  `button1` longtext DEFAULT NULL,
  `button2` longtext DEFAULT NULL,
  `button3` longtext DEFAULT NULL,
  `button4` longtext DEFAULT NULL,
  `button5` longtext DEFAULT NULL,
  `image_link` longtext DEFAULT NULL,
  `image_url` longtext DEFAULT NULL,
  `message_type` varchar(2) DEFAULT NULL,
  `msg` longtext NOT NULL,
  `msg_sms` longtext DEFAULT NULL,
  `only_sms` varchar(1) DEFAULT NULL COMMENT 'N : 카카오 전용, Y : SMS 전용, D : 카카오 발송후 실패시 SMS',
  `phn` varchar(15) NOT NULL,
  `profile` varchar(50) DEFAULT NULL,
  `p_com` varchar(2) DEFAULT NULL,
  `p_invoice` varchar(100) DEFAULT NULL,
  `reg_dt` varchar(20) NOT NULL,
  `remark1` varchar(50) DEFAULT NULL,
  `remark2` varchar(50) DEFAULT NULL,
  `remark3` varchar(50) DEFAULT NULL,
  `remark4` varchar(50) DEFAULT NULL,
  `remark5` varchar(50) DEFAULT NULL,
  `reserve_dt` varchar(14) NOT NULL,
  `sms_kind` varchar(1) DEFAULT NULL,
  `sms_lms_tit` varchar(120) DEFAULT NULL,
  `sms_sender` varchar(15) DEFAULT NULL,
  `s_code` varchar(2) DEFAULT NULL,
  `tmpl_id` varchar(30) DEFAULT NULL,
  `wide` varchar(1) DEFAULT NULL,
  `send_group` char(20) DEFAULT NULL,
  `supplement` mediumtext DEFAULT NULL,
  `price` int(11) DEFAULT NULL,
  `currency_type` char(3) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `header` varchar(100) DEFAULT NULL,
  `carousel` text DEFAULT NULL,
  `attachments` text DEFAULT NULL,
  `link` text DEFAULT NULL,
  `mms_image_id` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `msgid` (`msgid`) USING BTREE,
  KEY `send_group` (`send_group`) USING BTREE,
  KEY `DHN_REQUEST_AT_send_group_IDX` (`send_group`,`reserve_dt`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 문자발송 및 비즈메시지 결과저장용 DHN_RESULT 테이블

CREATE TABLE `DHN_RESULT` (
  `msgid` varchar(32) NOT NULL,
  `userid` varchar(20) NOT NULL,
  `ad_flag` varchar(1) DEFAULT NULL,
  `button1` longtext DEFAULT NULL,
  `button2` longtext DEFAULT NULL,
  `button3` longtext DEFAULT NULL,
  `button4` longtext DEFAULT NULL,
  `button5` longtext DEFAULT NULL,
  `code` varchar(4) DEFAULT NULL,
  `image_link` longtext DEFAULT NULL,
  `image_url` longtext DEFAULT NULL,
  `kind` varchar(1) DEFAULT NULL,
  `message` longtext DEFAULT NULL COMMENT '결과값 메시지(1차로 알림톡 2차로 문자를 보낼 시 2차 문자 결과값에 대한 메시지가 들어간다)',
  `message_type` varchar(2) DEFAULT NULL COMMENT '문자발송 타입(1차로 알림톡 2차로 문자를 보낼 시 2차 문자 타입인 PH가 적히게 된다)',
  `msg` longtext NOT NULL COMMENT '발송 결과값 메시지(1차로 알림톡 2차로 문자를 보낼 시 2차 문자의 결과값이 들어간다.)',
  `msg_sms` longtext DEFAULT NULL,
  `only_sms` varchar(1) DEFAULT NULL,
  `p_com` varchar(2) DEFAULT NULL,
  `p_invoice` varchar(100) DEFAULT NULL,
  `phn` varchar(15) NOT NULL,
  `profile` varchar(50) DEFAULT NULL,
  `reg_dt` varchar(20) NOT NULL,
  `remark1` varchar(50) DEFAULT NULL COMMENT '문자 수신 통신사',
  `remark2` varchar(50) DEFAULT NULL COMMENT '문자 발송 시간',
  `remark3` varchar(50) DEFAULT NULL COMMENT '1: 친구톡, 2: 알림톡',
  `remark4` varchar(50) DEFAULT NULL,
  `remark5` varchar(50) DEFAULT NULL,
  `res_dt` varchar(20) DEFAULT NULL,
  `reserve_dt` varchar(14) NOT NULL,
  `result` varchar(1) DEFAULT NULL,
  `s_code` varchar(4) DEFAULT NULL,
  `sms_kind` varchar(1) DEFAULT NULL,
  `sms_lms_tit` varchar(120) DEFAULT NULL,
  `sms_sender` varchar(15) DEFAULT NULL,
  `sync` varchar(1) NOT NULL,
  `tmpl_id` varchar(30) DEFAULT NULL,
  `wide` varchar(1) DEFAULT NULL,
  `send_group` varchar(20) DEFAULT NULL,
  `supplement` text DEFAULT NULL,
  `price` int(11) DEFAULT 0,
  `currency_type` char(3) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `header` varchar(50) DEFAULT NULL,
  `carousel` text DEFAULT NULL,
  `attachments` text DEFAULT NULL,
  `link` text DEFAULT NULL,
  `mms_image_id` varchar(100) DEFAULT NULL,
  `att_items` text DEFAULT NULL,
  `att_coupon` text DEFAULT NULL,
  UNIQUE KEY `DHN_RESULT_userid_IDX` (`userid`,`msgid`) USING BTREE,
  KEY `userid_result_sync` (`userid`,`sync`,`result`) USING BTREE,
  KEY `only_sms_result` (`result`,`only_sms`) USING BTREE,
  KEY `userid_remark4_result` (`result`,`userid`,`remark4`) USING BTREE,
  KEY `result_sync_send_group` (`send_group`,`result`,`sync`) USING BTREE,
  KEY `IDX_DHN_RESULT` (`userid`,`reg_dt`) USING BTREE,
  KEY `userid_result_send_group` (`userid`,`result`,`send_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- DHN_RESULT 백업을 위한 테이블

CREATE TABLE `DHN_RESULT_BK_TEMP` (
  `msgid` varchar(32) NOT NULL,
  `userid` varchar(20) NOT NULL,
  `ad_flag` varchar(1) DEFAULT NULL,
  `button1` longtext DEFAULT NULL,
  `button2` longtext DEFAULT NULL,
  `button3` longtext DEFAULT NULL,
  `button4` longtext DEFAULT NULL,
  `button5` longtext DEFAULT NULL,
  `code` varchar(4) DEFAULT NULL,
  `image_link` longtext DEFAULT NULL,
  `image_url` longtext DEFAULT NULL,
  `kind` varchar(1) DEFAULT NULL,
  `message` longtext DEFAULT NULL COMMENT '결과값 메시지(1차로 알림톡 2차로 문자를 보낼 시 2차 문자 결과값에 대한 메시지가 들어간다)',
  `message_type` varchar(2) DEFAULT NULL COMMENT '문자발송 타입(1차로 알림톡 2차로 문자를 보낼 시 2차 문자 타입인 PH가 적히게 된다)',
  `msg` longtext NOT NULL COMMENT '발송 결과값 메시지(1차로 알림톡 2차로 문자를 보낼 시 2차 문자의 결과값이 들어간다.)',
  `msg_sms` longtext DEFAULT NULL,
  `only_sms` varchar(1) DEFAULT NULL,
  `p_com` varchar(2) DEFAULT NULL,
  `p_invoice` varchar(100) DEFAULT NULL,
  `phn` varchar(15) NOT NULL,
  `profile` varchar(50) DEFAULT NULL,
  `reg_dt` varchar(20) NOT NULL,
  `remark1` varchar(50) DEFAULT NULL COMMENT '문자 수신 통신사',
  `remark2` varchar(50) DEFAULT NULL COMMENT '문자 발송 시간',
  `remark3` varchar(50) DEFAULT NULL COMMENT '1: 친구톡, 2: 알림톡',
  `remark4` varchar(50) DEFAULT NULL,
  `remark5` varchar(50) DEFAULT NULL,
  `res_dt` varchar(20) DEFAULT NULL,
  `reserve_dt` varchar(14) NOT NULL,
  `result` varchar(1) DEFAULT NULL,
  `s_code` varchar(4) DEFAULT NULL,
  `sms_kind` varchar(1) DEFAULT NULL,
  `sms_lms_tit` varchar(120) DEFAULT NULL,
  `sms_sender` varchar(15) DEFAULT NULL,
  `sync` varchar(1) NOT NULL,
  `tmpl_id` varchar(30) DEFAULT NULL,
  `wide` varchar(1) DEFAULT NULL,
  `send_group` varchar(20) DEFAULT NULL,
  `supplement` text DEFAULT NULL,
  `price` int(11) DEFAULT 0,
  `currency_type` char(3) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `header` varchar(50) DEFAULT NULL,
  `carousel` text DEFAULT NULL,
  `attachments` text DEFAULT NULL,
  `link` text DEFAULT NULL,
  `mms_image_id` varchar(100) DEFAULT NULL,
  `att_items` text DEFAULT NULL,
  `att_coupon` text DEFAULT NULL,
  KEY `IDX_DHN_RESULT` (`userid`,`reg_dt`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- kakao.DHN_RESULT_TEMP definition

CREATE TABLE `DHN_RESULT_TEMP` (
  `msgid` varchar(20) NOT NULL,
  `userid` varchar(20) NOT NULL,
  `ad_flag` varchar(1) DEFAULT NULL,
  `button1` longtext DEFAULT NULL,
  `button2` longtext DEFAULT NULL,
  `button3` longtext DEFAULT NULL,
  `button4` longtext DEFAULT NULL,
  `button5` longtext DEFAULT NULL,
  `code` varchar(4) DEFAULT NULL,
  `image_link` longtext DEFAULT NULL,
  `image_url` longtext DEFAULT NULL,
  `kind` varchar(1) DEFAULT NULL,
  `message` longtext DEFAULT NULL,
  `message_type` varchar(2) DEFAULT NULL,
  `msg` longtext NOT NULL,
  `msg_sms` longtext DEFAULT NULL,
  `only_sms` varchar(1) DEFAULT NULL,
  `p_com` varchar(2) DEFAULT NULL,
  `p_invoice` varchar(100) DEFAULT NULL,
  `phn` varchar(15) NOT NULL,
  `profile` varchar(50) DEFAULT NULL,
  `reg_dt` varchar(20) NOT NULL,
  `remark1` varchar(50) DEFAULT NULL,
  `remark2` varchar(50) DEFAULT NULL,
  `remark3` varchar(50) DEFAULT NULL,
  `remark4` varchar(50) DEFAULT NULL,
  `remark5` varchar(50) DEFAULT NULL,
  `res_dt` varchar(20) DEFAULT NULL,
  `reserve_dt` varchar(14) NOT NULL,
  `result` varchar(1) DEFAULT NULL,
  `s_code` varchar(2) DEFAULT NULL,
  `sms_kind` varchar(1) DEFAULT NULL,
  `sms_lms_tit` varchar(120) DEFAULT NULL,
  `sms_sender` varchar(15) DEFAULT NULL,
  `sync` varchar(1) NOT NULL,
  `tmpl_id` varchar(30) DEFAULT NULL,
  `wide` varchar(1) DEFAULT NULL,
  `send_group` varchar(20) DEFAULT NULL,
  `supplement` text DEFAULT NULL,
  `price` int(11) DEFAULT 0,
  `currency_type` char(3) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `header` varchar(50) DEFAULT NULL,
  `carousel` longtext DEFAULT NULL,
  `attachments` text DEFAULT NULL,
  `link` text DEFAULT NULL,
  `mms_image_id` varchar(100) DEFAULT NULL,
  `att_items` text DEFAULT NULL,
  `att_coupon` text DEFAULT NULL,
  PRIMARY KEY (`msgid`) USING BTREE,
  KEY `userid_result_sync` (`userid`,`sync`,`result`) USING BTREE,
  KEY `only_sms_result` (`result`,`only_sms`) USING BTREE,
  KEY `userid_remark4_result` (`result`,`userid`,`remark4`) USING BTREE,
  KEY `result_sync_send_group` (`send_group`,`result`,`sync`) USING BTREE,
  KEY `IDX_DHN_RESULT` (`userid`,`reg_dt`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- LG MMS (LMS) 발송용 LG_MMS_MSG 테이블

CREATE TABLE `LG_MMS_MSG` (
  `MSGKEY` int(11) NOT NULL AUTO_INCREMENT,
  `SUBJECT` varchar(120) DEFAULT NULL,
  `PHONE` varchar(15) NOT NULL,
  `CALLBACK` varchar(15) NOT NULL,
  `STATUS` varchar(2) NOT NULL DEFAULT '0',
  `REQDATE` datetime NOT NULL,
  `MSG` varchar(4000) DEFAULT NULL,
  `FILE_CNT` int(5) NOT NULL DEFAULT 0,
  `FILE_CNT_REAL` int(5) DEFAULT NULL,
  `FILE_PATH1` varchar(512) DEFAULT NULL,
  `FILE_PATH1_SIZ` int(10) DEFAULT NULL,
  `FILE_PATH2` varchar(512) DEFAULT NULL,
  `FILE_PATH2_SIZ` int(10) DEFAULT NULL,
  `FILE_PATH3` varchar(512) DEFAULT NULL,
  `FILE_PATH3_SIZ` int(10) DEFAULT NULL,
  `FILE_PATH4` varchar(512) DEFAULT NULL,
  `FILE_PATH4_SIZ` int(10) DEFAULT NULL,
  `FILE_PATH5` varchar(512) DEFAULT NULL,
  `FILE_PATH5_SIZ` int(10) DEFAULT NULL,
  `EXPIRETIME` varchar(10) NOT NULL DEFAULT '43200',
  `SENTDATE` datetime DEFAULT NULL,
  `RSLTDATE` datetime DEFAULT NULL,
  `REPORTDATE` datetime DEFAULT NULL,
  `TERMINATEDDATE` datetime DEFAULT NULL,
  `RSLT` varchar(4) DEFAULT NULL,
  `TYPE` varchar(2) NOT NULL DEFAULT '0',
  `TELCOINFO` varchar(10) DEFAULT NULL,
  `ROUTE_ID` varchar(20) DEFAULT NULL,
  `ID` varchar(20) DEFAULT NULL,
  `POST` varchar(20) DEFAULT NULL,
  `ETC1` varchar(64) DEFAULT NULL,
  `ETC2` varchar(32) DEFAULT NULL,
  `ETC3` varchar(32) DEFAULT NULL,
  `ETC4` int(10) DEFAULT NULL,
  `MULTI_SEQ` varchar(10) DEFAULT NULL,
  `KISA_ORIGCODE` varchar(10) DEFAULT NULL,
  `REAL_ID` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`MSGKEY`),
  KEY `LG_MMS_MSG_IDX2` (`STATUS`,`REQDATE`),
  KEY `LG_MMS_MSG_IDX3` (`PHONE`),
  KEY `LG_MMS_MSG_IDX4` (`REQDATE`,`RSLT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- LG SMS 발송용 LG_SC_TRAN 테이블

CREATE TABLE `LG_SC_TRAN` (
  `TR_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `TR_SENDDATE` datetime DEFAULT NULL,
  `TR_ID` varchar(16) DEFAULT NULL,
  `TR_SENDSTAT` varchar(1) NOT NULL DEFAULT '0',
  `TR_RSLTSTAT` varchar(2) DEFAULT '00',
  `TR_MSGTYPE` varchar(1) NOT NULL DEFAULT '0',
  `TR_PHONE` varchar(20) NOT NULL DEFAULT '',
  `TR_CALLBACK` varchar(20) NOT NULL DEFAULT '',
  `TR_RSLTDATE` datetime DEFAULT NULL,
  `TR_MODIFIED` datetime DEFAULT NULL,
  `TR_MSG` varchar(160) DEFAULT NULL,
  `TR_NET` varchar(4) DEFAULT NULL,
  `TR_ETC1` varchar(160) DEFAULT NULL,
  `TR_ETC2` varchar(160) DEFAULT NULL,
  `TR_ETC3` varchar(160) DEFAULT NULL,
  `TR_ETC4` varchar(160) DEFAULT NULL,
  `TR_ETC5` varchar(160) DEFAULT NULL,
  `TR_ETC6` varchar(160) DEFAULT NULL,
  `TR_ROUTEID` varchar(20) DEFAULT NULL,
  `TR_REALSENDDATE` datetime DEFAULT NULL,
  `TR_KISAORIGCODE` varchar(10) DEFAULT NULL,
  `TR_REALID` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`TR_NUM`),
  KEY `LG_SC_TRAN_IDX1` (`TR_SENDSTAT`,`TR_SENDDATE`),
  KEY `LG_SC_TRAN_IDX2` (`TR_PHONE`),
  KEY `LG_SC_TRAN_IDX3` (`TR_SENDDATE`,`TR_RSLTSTAT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- LG OTP SMS 발송용 LG_OTP_SC_TRAN 테이블

CREATE TABLE `LG_OTP_SC_TRAN` (
  `TR_NUM` int(11) NOT NULL AUTO_INCREMENT,
  `TR_SENDDATE` datetime DEFAULT NULL,
  `TR_ID` varchar(16) DEFAULT NULL,
  `TR_SENDSTAT` varchar(1) NOT NULL DEFAULT '0',
  `TR_RSLTSTAT` varchar(2) DEFAULT '00',
  `TR_MSGTYPE` varchar(1) NOT NULL DEFAULT '0',
  `TR_PHONE` varchar(20) NOT NULL DEFAULT '',
  `TR_CALLBACK` varchar(20) NOT NULL DEFAULT '',
  `TR_RSLTDATE` datetime DEFAULT NULL,
  `TR_MODIFIED` datetime DEFAULT NULL,
  `TR_MSG` varchar(160) DEFAULT NULL,
  `TR_NET` varchar(4) DEFAULT NULL,
  `TR_ETC1` varchar(160) DEFAULT NULL,
  `TR_ETC2` varchar(160) DEFAULT NULL,
  `TR_ETC3` varchar(160) DEFAULT NULL,
  `TR_ETC4` varchar(160) DEFAULT NULL,
  `TR_ETC5` varchar(160) DEFAULT NULL,
  `TR_ETC6` varchar(160) DEFAULT NULL,
  `TR_ROUTEID` varchar(20) DEFAULT NULL,
  `TR_REALSENDDATE` datetime DEFAULT NULL,
  `TR_KISAORIGCODE` varchar(10) DEFAULT NULL,
  `TR_REALID` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`TR_NUM`),
  KEY `LG_OTP_SC_TRAN_IDX1` (`TR_SENDSTAT`,`TR_SENDDATE`),
  KEY `LG_OTP_SC_TRAN_IDX2` (`TR_PHONE`),
  KEY `LG_OTP_SC_TRAN_IDX3` (`TR_SENDDATE`,`TR_RSLTSTAT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- LG OTP MMS (LMS) 발송용 LG_OTP_MMS_MSG 테이블

CREATE TABLE `LG_OTP_MMS_MSG` (
  `MSGKEY` int(11) NOT NULL AUTO_INCREMENT,
  `SUBJECT` varchar(120) DEFAULT NULL,
  `PHONE` varchar(15) NOT NULL,
  `CALLBACK` varchar(15) NOT NULL,
  `STATUS` varchar(2) NOT NULL DEFAULT '0',
  `REQDATE` datetime NOT NULL,
  `MSG` varchar(4000) DEFAULT NULL,
  `FILE_CNT` int(5) NOT NULL DEFAULT 0,
  `FILE_CNT_REAL` int(5) DEFAULT NULL,
  `FILE_PATH1` varchar(512) DEFAULT NULL,
  `FILE_PATH1_SIZ` int(10) DEFAULT NULL,
  `FILE_PATH2` varchar(512) DEFAULT NULL,
  `FILE_PATH2_SIZ` int(10) DEFAULT NULL,
  `FILE_PATH3` varchar(512) DEFAULT NULL,
  `FILE_PATH3_SIZ` int(10) DEFAULT NULL,
  `FILE_PATH4` varchar(512) DEFAULT NULL,
  `FILE_PATH4_SIZ` int(10) DEFAULT NULL,
  `FILE_PATH5` varchar(512) DEFAULT NULL,
  `FILE_PATH5_SIZ` int(10) DEFAULT NULL,
  `EXPIRETIME` varchar(10) NOT NULL DEFAULT '43200',
  `SENTDATE` datetime DEFAULT NULL,
  `RSLTDATE` datetime DEFAULT NULL,
  `REPORTDATE` datetime DEFAULT NULL,
  `TERMINATEDDATE` datetime DEFAULT NULL,
  `RSLT` varchar(4) DEFAULT NULL,
  `TYPE` varchar(2) NOT NULL DEFAULT '0',
  `TELCOINFO` varchar(10) DEFAULT NULL,
  `ROUTE_ID` varchar(20) DEFAULT NULL,
  `ID` varchar(20) DEFAULT NULL,
  `POST` varchar(20) DEFAULT NULL,
  `ETC1` varchar(64) DEFAULT NULL,
  `ETC2` varchar(32) DEFAULT NULL,
  `ETC3` varchar(32) DEFAULT NULL,
  `ETC4` int(10) DEFAULT NULL,
  `MULTI_SEQ` varchar(10) DEFAULT NULL,
  `KISA_ORIGCODE` varchar(10) DEFAULT NULL,
  `REAL_ID` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`MSGKEY`),
  KEY `LG_OTP_MMS_MSG_IDX2` (`STATUS`,`REQDATE`),
  KEY `LG_OTP_MMS_MSG_IDX3` (`PHONE`),
  KEY `LG_OTP_MMS_MSG_IDX4` (`REQDATE`,`RSLT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Oshot SMS
CREATE TABLE `OShotSMS` (
  `MsgID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Sender` varchar(15) NOT NULL,
  `Receiver` varchar(15) NOT NULL,
  `Msg` varchar(120) NOT NULL,
  `URL` varchar(80) DEFAULT NULL,
  `ReserveDT` datetime DEFAULT NULL,
  `TimeoutDT` datetime DEFAULT NULL,
  `SendDT` datetime DEFAULT NULL,
  `SendResult` smallint(6) NOT NULL DEFAULT 0,
  `Telecom` varchar(7) DEFAULT NULL,
  `InsertDT` timestamp NOT NULL DEFAULT current_timestamp(),
  `IdentityCode` varchar(30) DEFAULT NULL,
  `Etc1` varchar(20) DEFAULT NULL,
  `Etc2` varchar(20) DEFAULT NULL,
  `Etc3` varchar(20) DEFAULT NULL,
  `cb_msg_id` varchar(100) DEFAULT NULL,
  `proc_flag` varchar(1) DEFAULT 'Y',
  `mst_id` int(11) DEFAULT NULL,
  `userid` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`MsgID`),
  KEY `IDX_OShotSMS` (`SendResult`,`ReserveDT`),
  KEY `OShotSMS_proc_flag_IDX` (`proc_flag`) USING BTREE,
  KEY `OShotSMS_cb_msg_id_IDX` (`cb_msg_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Oshot MMS
CREATE TABLE `OShotMMS` (
  `MsgID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `MsgGroupID` varchar(20) NOT NULL,
  `Sender` varchar(15) NOT NULL,
  `Receiver` varchar(15) NOT NULL,
  `Subject` varchar(120) DEFAULT NULL,
  `Msg` varchar(4000) NOT NULL,
  `ReserveDT` datetime DEFAULT NULL,
  `TimeoutDT` datetime DEFAULT NULL,
  `SendDT` datetime DEFAULT NULL,
  `SendResult` smallint(6) NOT NULL DEFAULT 0,
  `Telecom` varchar(7) DEFAULT NULL,
  `File_Path1` varchar(128) DEFAULT NULL,
  `File_Path2` varchar(128) DEFAULT NULL,
  `File_Path3` varchar(128) DEFAULT NULL,
  `File_Path4` varchar(128) DEFAULT NULL,
  `InsertDT` timestamp NOT NULL DEFAULT current_timestamp(),
  `IdentityCode` varchar(30) DEFAULT NULL,
  `Etc1` varchar(20) DEFAULT NULL,
  `Etc2` varchar(20) DEFAULT NULL,
  `Etc3` varchar(20) DEFAULT NULL,
  `cb_msg_id` varchar(100) DEFAULT NULL,
  `proc_flag` varchar(1) DEFAULT 'Y',
  `mst_id` int(11) DEFAULT NULL,
  `userid` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`MsgID`),
  KEY `IDX_OShotMMS` (`SendResult`,`ReserveDT`,`MsgGroupID`),
  KEY `OShotMMS_proc_flag_IDX` (`proc_flag`) USING BTREE,
  KEY `OShotMMS_cb_msg_id_IDX` (`cb_msg_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- Oshot 오샷 발송 테이블

CREATE TABLE `OShotMSG` (
  `MsgID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '메시지PK',
  `MsgGroupID` varchar(20) NOT NULL,
  `SendType` varchar(10) NOT NULL,
  `Sender` varchar(15) NOT NULL,
  `Receiver` varchar(15) NOT NULL,
  `Subject` varchar(120) DEFAULT '',
  `Msg` varchar(4000) NOT NULL,
  `ReserveDT` datetime DEFAULT NULL,
  `TimeoutDT` datetime DEFAULT NULL,
  `SendDT` datetime DEFAULT NULL,
  `InsertDT` timestamp NOT NULL DEFAULT current_timestamp(),
  `UpdateDT` datetime DEFAULT NULL,
  `Telecom` varchar(7) DEFAULT NULL,
  `SendResult` smallint(6) NOT NULL DEFAULT 0,
  `KakaoResult` smallint(6) DEFAULT NULL,
  `QStatus` varchar(10) DEFAULT NULL,
  `ResultMsg` varchar(300) DEFAULT NULL,
  `URL` varchar(80) DEFAULT NULL,
  `File_Path1` varchar(128) DEFAULT NULL,
  `File_Path2` varchar(128) DEFAULT NULL,
  `File_Path3` varchar(128) DEFAULT NULL,
  `File_Path4` varchar(128) DEFAULT NULL,
  `FilePath` varchar(512) DEFAULT NULL,
  `MsgType` varchar(2) DEFAULT NULL,
  `kko_btn_info` varchar(4000) DEFAULT NULL,
  `img_url` varchar(200) DEFAULT NULL,
  `img_link` varchar(100) DEFAULT NULL,
  `FailOver` varchar(1) DEFAULT NULL,
  `ReplaceMsg` varchar(2000) DEFAULT NULL,
  `KakaoMethod` varchar(1) DEFAULT NULL,
  `SenderKey` varchar(40) DEFAULT NULL,
  `TemplateCode` varchar(30) DEFAULT NULL,
  `IdentityCode` varchar(30) DEFAULT NULL,
  `Etc1` varchar(20) DEFAULT NULL,
  `Etc2` varchar(20) DEFAULT NULL,
  `Etc3` varchar(20) DEFAULT NULL,
  `SendResultSub` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`MsgID`),
  KEY `IDX_OShotMSG` (`SendResult`,`ReserveDT`,`MsgGroupID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='메시지큐';

-- Oshot 오샷 OTP 발송 테이블

CREATE TABLE `OTP_OShotMSG` (
  `MsgID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '메시지PK',
  `MsgGroupID` varchar(20) NOT NULL,
  `SendType` varchar(10) NOT NULL,
  `Sender` varchar(15) NOT NULL,
  `Receiver` varchar(15) NOT NULL,
  `Subject` varchar(120) DEFAULT '',
  `Msg` varchar(4000) NOT NULL,
  `ReserveDT` datetime DEFAULT NULL,
  `TimeoutDT` datetime DEFAULT NULL,
  `SendDT` datetime DEFAULT NULL,
  `InsertDT` timestamp NOT NULL DEFAULT current_timestamp(),
  `UpdateDT` datetime DEFAULT NULL,
  `Telecom` varchar(7) DEFAULT NULL,
  `SendResult` smallint(6) NOT NULL DEFAULT 0,
  `KakaoResult` smallint(6) DEFAULT NULL,
  `QStatus` varchar(10) DEFAULT NULL,
  `ResultMsg` varchar(300) DEFAULT NULL,
  `URL` varchar(80) DEFAULT NULL,
  `File_Path1` varchar(128) DEFAULT NULL,
  `File_Path2` varchar(128) DEFAULT NULL,
  `File_Path3` varchar(128) DEFAULT NULL,
  `File_Path4` varchar(128) DEFAULT NULL,
  `FilePath` varchar(512) DEFAULT NULL,
  `MsgType` varchar(2) DEFAULT NULL,
  `kko_btn_info` varchar(4000) DEFAULT NULL,
  `img_url` varchar(200) DEFAULT NULL,
  `img_link` varchar(100) DEFAULT NULL,
  `FailOver` varchar(1) DEFAULT NULL,
  `ReplaceMsg` varchar(2000) DEFAULT NULL,
  `KakaoMethod` varchar(1) DEFAULT NULL,
  `SenderKey` varchar(40) DEFAULT NULL,
  `TemplateCode` varchar(30) DEFAULT NULL,
  `IdentityCode` varchar(30) DEFAULT NULL,
  `Etc1` varchar(20) DEFAULT NULL,
  `Etc2` varchar(20) DEFAULT NULL,
  `Etc3` varchar(20) DEFAULT NULL,
  `SendResultSub` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`MsgID`),
  KEY `IDX_OShotMSG` (`SendResult`,`ReserveDT`,`MsgGroupID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='메시지큐';

-- MMS발송용 이미지용 api_mms_images 테이블

CREATE TABLE `api_mms_images` (
  `user_id` varchar(100) DEFAULT NULL,
  `mms_id` varchar(100) DEFAULT NULL,
  `origin1_path` text DEFAULT NULL,
  `origin2_path` text DEFAULT NULL,
  `origin3_path` text DEFAULT NULL,
  `file1_path` text DEFAULT NULL,
  `file2_path` text DEFAULT NULL,
  `file3_path` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 불필요 문자 제거? 용 SPECIAL_CHARACTER 테이블

CREATE TABLE `SPECIAL_CHARACTER` (
  `orgin_hex_code` varchar(100) DEFAULT NULL,
  `dest_str` varchar(100) DEFAULT NULL,
  `enabled` varchar(1) NOT NULL DEFAULT 'Y',
  UNIQUE KEY `SPECIAL_CHARACTER_orgin_hex_code_IDX` (`orgin_hex_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 문자체크 insert문

INSERT INTO SPECIAL_CHARACTER
(orgin_hex_code, dest_str, enabled)
VALUES('C2A0', NULL, 'Y'),('E280A8', NULL, 'Y'),('E280A4', '·', 'Y'),('E29E9F', '→', 'Y'),('E29C94', '√', 'Y'),('E280A3', '·', 'Y'),('EFBBBF', NULL, 'Y');

-- 알림톡 9999 에러 재발송 테이블

CREATE TABLE `DHN_REQUEST_AT_RESEND` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `msgid` varchar(32) NOT NULL,
  `userid` varchar(20) NOT NULL,
  `ad_flag` varchar(1) DEFAULT NULL,
  `button1` longtext DEFAULT NULL,
  `button2` longtext DEFAULT NULL,
  `button3` longtext DEFAULT NULL,
  `button4` longtext DEFAULT NULL,
  `button5` longtext DEFAULT NULL,
  `image_link` longtext DEFAULT NULL,
  `image_url` longtext DEFAULT NULL,
  `message_type` varchar(2) DEFAULT NULL,
  `msg` longtext NOT NULL,
  `msg_sms` longtext DEFAULT NULL,
  `only_sms` varchar(1) DEFAULT NULL COMMENT 'N : 카카오 전용, Y : SMS 전용, D : 카카오 발송후 실패시 SMS',
  `phn` varchar(15) NOT NULL,
  `profile` varchar(50) DEFAULT NULL,
  `p_com` varchar(2) DEFAULT NULL,
  `p_invoice` varchar(100) DEFAULT NULL,
  `reg_dt` varchar(20) NOT NULL,
  `remark1` varchar(50) DEFAULT NULL,
  `remark2` varchar(50) DEFAULT NULL,
  `remark3` varchar(50) DEFAULT NULL,
  `remark4` varchar(50) DEFAULT NULL,
  `remark5` varchar(50) DEFAULT NULL,
  `reserve_dt` varchar(14) NOT NULL,
  `sms_kind` varchar(1) DEFAULT NULL,
  `sms_lms_tit` varchar(120) DEFAULT NULL,
  `sms_sender` varchar(15) DEFAULT NULL,
  `s_code` varchar(2) DEFAULT NULL,
  `tmpl_id` varchar(30) DEFAULT NULL,
  `wide` varchar(1) DEFAULT NULL,
  `send_group` char(20) DEFAULT NULL,
  `supplement` mediumtext DEFAULT NULL,
  `price` int(11) DEFAULT NULL,
  `currency_type` char(3) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `header` varchar(100) DEFAULT NULL,
  `carousel` text DEFAULT NULL,
  `attachments` text DEFAULT NULL,
  `link` text DEFAULT NULL,
  `mms_image_id` varchar(100) DEFAULT NULL,
  `real_msgid` varchar(32) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `msgid` (`msgid`) USING BTREE,
  KEY `send_group` (`send_group`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 친구톡 9999 에러 재발송 테이블

CREATE TABLE `DHN_REQUEST_RESEND` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `msgid` varchar(32) NOT NULL,
  `userid` varchar(20) NOT NULL,
  `ad_flag` varchar(1) DEFAULT NULL,
  `button1` longtext DEFAULT NULL,
  `button2` longtext DEFAULT NULL,
  `button3` longtext DEFAULT NULL,
  `button4` longtext DEFAULT NULL,
  `button5` longtext DEFAULT NULL,
  `image_link` longtext DEFAULT NULL,
  `image_url` longtext DEFAULT NULL,
  `message_type` varchar(2) DEFAULT NULL,
  `msg` longtext NOT NULL,
  `msg_sms` longtext DEFAULT NULL,
  `only_sms` varchar(1) DEFAULT NULL COMMENT 'N : 카카오 전용, Y : SMS 전용, D : 카카오 발송후 실패시 SMS',
  `phn` varchar(15) NOT NULL,
  `profile` varchar(50) DEFAULT NULL,
  `p_com` varchar(2) DEFAULT NULL,
  `p_invoice` varchar(100) DEFAULT NULL,
  `reg_dt` varchar(20) NOT NULL,
  `remark1` varchar(50) DEFAULT NULL,
  `remark2` varchar(50) DEFAULT NULL,
  `remark3` varchar(50) DEFAULT NULL,
  `remark4` varchar(50) DEFAULT NULL,
  `remark5` varchar(50) DEFAULT NULL,
  `reserve_dt` varchar(14) NOT NULL,
  `sms_kind` varchar(1) DEFAULT NULL,
  `sms_lms_tit` varchar(120) DEFAULT NULL,
  `sms_sender` varchar(15) DEFAULT NULL,
  `s_code` varchar(2) DEFAULT NULL,
  `tmpl_id` varchar(30) DEFAULT NULL,
  `wide` varchar(1) DEFAULT NULL,
  `send_group` char(20) DEFAULT NULL,
  `supplement` text DEFAULT NULL,
  `price` int(11) DEFAULT 0,
  `currency_type` char(3) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `header` varchar(100) DEFAULT NULL,
  `carousel` longtext DEFAULT NULL,
  `attachments` text DEFAULT NULL,
  `att_items` text DEFAULT NULL,
  `att_coupon` text DEFAULT NULL,
  `mms_image_id` varchar(100) DEFAULT NULL,
  `real_msgid` varchar(32) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `msgid` (`msgid`) USING BTREE,
  KEY `send_group` (`send_group`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 통계 테이블

CREATE TABLE `DHN_RESULT_STA` (
  `userid` varchar(255) NOT NULL COMMENT '발송계정',
  `depart` varchar(100) DEFAULT NULL COMMENT '발송 부서 코드',
  `send_cnt` decimal(10,0) DEFAULT 0 COMMENT '발송 Count(SMS, MMS 대기 Count 제외)',
  `send_date` varchar(255) NOT NULL COMMENT '발송일자',
  `ats_cnt` int(11) DEFAULT 0 COMMENT '알림톡 성공 Count',
  `ate_cnt` int(11) DEFAULT 0 COMMENT '알림톡 실패 Count',
  `fts_cnt` int(11) DEFAULT 0 COMMENT '친구톡 성공 Count',
  `fte_cnt` int(11) DEFAULT 0 COMMENT '친구톡 실패 Count',
  `ftis_cnt` int(11) DEFAULT 0 COMMENT '친구톡 이미지 성공 Count',
  `ftie_cnt` int(11) DEFAULT 0 COMMENT '친구톡 이미지 실패 Count',
  `ftws_cnt` int(11) DEFAULT 0 COMMENT '친구톡 와이드 성공 Count',
  `ftwe_cnt` int(11) DEFAULT 0 COMMENT '친구톡 와이드 실패 Count',
  `smss_cnt` int(11) DEFAULT 0 COMMENT 'SMS 성공 Count',
  `smsd_cnt` int(11) DEFAULT 0 COMMENT 'SMS 대기 Count',
  `smse_cnt` int(11) DEFAULT 0 COMMENT 'SMS 실패 Count',
  `lmss_cnt` int(11) DEFAULT 0 COMMENT 'LMS 성공 Count',
  `lmsd_cnt` int(11) DEFAULT 0 COMMENT 'LMS 대기 Count',
  `lmse_cnt` int(11) DEFAULT 0 COMMENT 'LMS 실패 Count',
  `mmss_cnt` int(11) DEFAULT 0 COMMENT 'MMS 성공 Count',
  `mmsd_cnt` int(11) DEFAULT 0 COMMENT 'MMS 대기 Count',
  `mmse_cnt` int(11) DEFAULT 0 COMMENT 'MMS 실패 Count',
  KEY `DHN_RESULT_SUM_send_date_IDX` (`send_date`,`userid`,`depart`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='카카오 발송 결과 통계';
